insert into Car (ID, CAR_ABILLITY_OVERALL, CHASSIS, ENGINE, NAME) values (3,	22,	3,	42,	'Jarno Zopfi');
insert into Car (ID, CAR_ABILLITY_OVERALL, CHASSIS, ENGINE, NAME) values (4,	38,	58,	19,	'Mees van de Rijdt');
insert into Car (ID, CAR_ABILLITY_OVERALL, CHASSIS, ENGINE, NAME) values (5,	46,	47,	45,	'Bira Van Haver');
insert into Car (ID, CAR_ABILLITY_OVERALL, CHASSIS, ENGINE, NAME) values (6,	70,	81,	59,	'Melvin Ezinga');
insert into Car (ID, CAR_ABILLITY_OVERALL, CHASSIS, ENGINE, NAME) values (7,	33,	50,	16,	'Rick Bogaards');
insert into Car (ID, CAR_ABILLITY_OVERALL, CHASSIS, ENGINE, NAME) values (8,	41,	34,	49,	'Laurens Weber');
insert into Car (ID, CAR_ABILLITY_OVERALL, CHASSIS, ENGINE, NAME) values (9,	32,	43,	21,	'Benjamin van Hees');
insert into Car (ID, CAR_ABILLITY_OVERALL, CHASSIS, ENGINE, NAME) values (10,	33,	35,	32,	'Mitchell van Dijk');
insert into Car (ID, CAR_ABILLITY_OVERALL, CHASSIS, ENGINE, NAME) values (11,	69,	59,	80,	'Esmee Kosterman');
insert into Car (ID, CAR_ABILLITY_OVERALL, CHASSIS, ENGINE, NAME) values (12,	58,	68,	49,	'Max Knapen');
insert into Car (ID, CAR_ABILLITY_OVERALL, CHASSIS, ENGINE, NAME) values (13,	39,	18,	60,	'Daan Richartz');
insert into Car (ID, CAR_ABILLITY_OVERALL, CHASSIS, ENGINE, NAME) values (14,	35,	60,	10,	'Dani van Ruiten');